/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetodepoo;

import br.edu.principal.TelaInicial;

/**
 *
 * @author Aluno
 */
public class JogodaOld extends javax.swing.JFrame {
    public boolean jogadorA = true;
    public boolean jogadorB = true;
    public int contpos=0;
    public int k=0, i=0;
    int op;
    public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal1, diagonal2;
    String[][] posicao = new String[3][3];

    /**
     * Creates new form JogodaOld
     */
    public JogodaOld() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoum = new javax.swing.JButton();
        botaodois = new javax.swing.JButton();
        botaoquatro = new javax.swing.JButton();
        botaocinco = new javax.swing.JButton();
        botaoseis = new javax.swing.JButton();
        botaosete = new javax.swing.JButton();
        botaooito = new javax.swing.JButton();
        botaotres = new javax.swing.JButton();
        botaonove = new javax.swing.JButton();
        Reiniciar = new javax.swing.JButton();
        visor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        botaoum.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaoum.setForeground(new java.awt.Color(0, 40, 191));
        botaoum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoumActionPerformed(evt);
            }
        });

        botaodois.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaodois.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaodois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodoisActionPerformed(evt);
            }
        });

        botaoquatro.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaoquatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoquatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoquatroActionPerformed(evt);
            }
        });

        botaocinco.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaocinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaocinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocincoActionPerformed(evt);
            }
        });

        botaoseis.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaoseis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoseisActionPerformed(evt);
            }
        });

        botaosete.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaosete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaosete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoseteActionPerformed(evt);
            }
        });

        botaooito.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaooito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaooito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaooitoActionPerformed(evt);
            }
        });

        botaotres.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaotres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaotres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaotresActionPerformed(evt);
            }
        });

        botaonove.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        botaonove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaonove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaonoveActionPerformed(evt);
            }
        });

        Reiniciar.setBackground(new java.awt.Color(102, 102, 255));
        Reiniciar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Reiniciar.setText("Reiniciar");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        visor.setEditable(false);
        visor.setBackground(new java.awt.Color(204, 204, 255));
        visor.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        visor.setForeground(new java.awt.Color(51, 51, 51));
        visor.setText("Começando pelo jogador X");
        visor.setAlignmentY(1.0F);
        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 40, 135));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Jogo da Old");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botaoum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botaodois, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botaotres, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(botaoquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botaocinco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(botaosete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botaooito, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botaoseis, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botaonove, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaodois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaotres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoum, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaocinco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoseis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaosete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaooito, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaonove, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botaoum.getAccessibleContext().setAccessibleName("botaoum");
        botaodois.getAccessibleContext().setAccessibleName("botaodois");
        botaoquatro.getAccessibleContext().setAccessibleName("botaoquatro");
        botaocinco.getAccessibleContext().setAccessibleName("botaocinco");
        botaoseis.getAccessibleContext().setAccessibleName("botaoseis");
        botaosete.getAccessibleContext().setAccessibleName("botaosete");
        botaooito.getAccessibleContext().setAccessibleName("botaooito");
        botaotres.getAccessibleContext().setAccessibleName("botaotres");
        botaonove.getAccessibleContext().setAccessibleName("botaonove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void jogadordavez (){
        if(jogadorA && jogadorB){
            this.op=1;
            jogadorA = false;
            jogadorB = true;
            visor.setText("Vez do Jogador O");
        }
        
        else if(jogadorA&&jogadorB==false){
            this.op=1;
            jogadorA=false;
            jogadorB=true;
            visor.setText("Vez do Jogador O");
        }
        else{
            this.op=2;
            jogadorA = true;
            jogadorB = false;
            visor.setText("Vez do Jogador X");
        }
    }
    
    public void limpaPosicao(){
        for(i=0;i<3;i++){
            for(k=0;k<3;k++){
                posicao[i][k]="";
            }        
        }
    }
    
    public void vencedor(){
        linha1=posicao[0][0]+posicao[0][1]+posicao[0][2];
        linha2=posicao[1][0]+posicao[1][1]+posicao[1][2];
        linha3=posicao[2][0]+posicao[2][1]+posicao[2][2];
        coluna1=posicao[0][0]+posicao[1][0]+posicao[2][0];
        coluna2=posicao[0][1]+posicao[1][1]+posicao[2][1];
        coluna3=posicao[0][2]+posicao[1][2]+posicao[2][2];
        diagonal1=posicao[0][0]+posicao[1][1]+posicao[2][2];
        diagonal2=posicao[0][2]+posicao[1][1]+posicao[2][0];
        
        if(linha1.equals("xxx")|linha1.equals("xxx")|linha1.equals("xxx")){
            visor.setText("X é o vencedor");
            botaoum.setEnabled(false);
            botaodois.setEnabled(false);
            botaotres.setEnabled(false);
            botaoquatro.setEnabled(false);
            botaocinco.setEnabled(false);
            botaoseis.setEnabled(false);
            botaosete.setEnabled(false);
            botaooito.setEnabled(false);
            botaonove.setEnabled(false);
        }
        
        if(coluna1.equals("xxx")|coluna2.equals("xxx")|coluna3.equals("xxx")){
            visor.setText("X é o vencedor");
            botaoum.setEnabled(false);
            botaodois.setEnabled(false);
            botaotres.setEnabled(false);
            botaoquatro.setEnabled(false);
            botaocinco.setEnabled(false);
            botaoseis.setEnabled(false);
            botaosete.setEnabled(false);
            botaooito.setEnabled(false);
            botaonove.setEnabled(false);
        }
        
        if(diagonal1.equals("xxx")|diagonal2.equals("xxx")){
            visor.setText("X é o vencedor");
            botaoum.setEnabled(false);
            botaodois.setEnabled(false);
            botaotres.setEnabled(false);
            botaoquatro.setEnabled(false);
            botaocinco.setEnabled(false);
            botaoseis.setEnabled(false);
            botaosete.setEnabled(false);
            botaooito.setEnabled(false);
            botaonove.setEnabled(false);
        }
        
        if(linha1.equals("ooo")|linha2.equals("ooo")|linha3.equals("ooo")){
            visor.setText("O é o vencedor");
            botaoum.setEnabled(false);
            botaodois.setEnabled(false);
            botaotres.setEnabled(false);
            botaoquatro.setEnabled(false);
            botaocinco.setEnabled(false);
            botaoseis.setEnabled(false);
            botaosete.setEnabled(false);
            botaooito.setEnabled(false);
            botaonove.setEnabled(false);
        }
        
        if(coluna1.equals("ooo")|coluna2.equals("ooo")|coluna3.equals("ooo")){
            visor.setText("O é o vencedor");
            botaoum.setEnabled(false);
            botaodois.setEnabled(false);
            botaotres.setEnabled(false);
            botaoquatro.setEnabled(false);
            botaocinco.setEnabled(false);
            botaoseis.setEnabled(false);
            botaosete.setEnabled(false);
            botaooito.setEnabled(false);
            botaonove.setEnabled(false);
        }
        
        if(diagonal1.equals("ooo")|diagonal2.equals("ooo")){
            visor.setText("O é o vencedor");
            botaoum.setEnabled(false);
            botaodois.setEnabled(false);
            botaotres.setEnabled(false);
            botaoquatro.setEnabled(false);
            botaocinco.setEnabled(false);
            botaoseis.setEnabled(false);
            botaosete.setEnabled(false);
            botaooito.setEnabled(false);
            botaonove.setEnabled(false);
        }
        
        else {
            if ((coluna1.length() == 3) && (coluna2.length() == 3) && (coluna3.length() == 3)) {
                visor.setText("A Old venceu");
            }
        }
    }
    
    private void botaoumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoumActionPerformed
        //botaoum 
        jogadordavez();
        if(op==1){
            botaoum.setText("X");
            botaoum.setEnabled(false);
            posicao[0][0]="x";
        }
        else{
            botaoum.setText("O");
            botaoum.setEnabled(false);
            posicao[0][0]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaoumActionPerformed
    // TODO add your handling code here:
    // TODO add your handling code here:
    
    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed
    
    private void botaodoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodoisActionPerformed
        //botaodois
        jogadordavez();
        if(op==1){
            botaodois.setText("X");
            botaodois.setEnabled(false);
            posicao[0][1]="x";
        }
        else{
            botaodois.setText("O");
            botaodois.setEnabled(false);
            posicao[0][1]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaodoisActionPerformed

    private void botaotresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaotresActionPerformed
        //botaotres
        jogadordavez();
        if(op==1){
            botaotres.setText("X");
            botaotres.setEnabled(false);
            posicao[0][2]="x";
        }
        else{
            botaotres.setText("O");
            botaotres.setEnabled(false);
            posicao[0][2]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaotresActionPerformed

    private void botaoquatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoquatroActionPerformed
        //botaoquatro
        jogadordavez();
        if(op==1){
            botaoquatro.setText("X");
            botaoquatro.setEnabled(false);
            posicao[1][0]="x";
        }
        else{
            botaoquatro.setText("O");
            botaoquatro.setEnabled(false);
            posicao[1][0]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaoquatroActionPerformed

    private void botaocincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocincoActionPerformed
        //botaocinco
        jogadordavez();
        if(op==1){
            botaocinco.setText("X");
            botaocinco.setEnabled(false);
            posicao[1][1]="x";
        }
        else{
            botaocinco.setText("O");
            botaocinco.setEnabled(false);
            posicao[1][1]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaocincoActionPerformed

    private void botaoseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoseisActionPerformed
        //botaoseis
        jogadordavez();
        if(op==1){
            botaoseis.setText("X");
            botaoseis.setEnabled(false);
            posicao[1][2]="x";
        }
        else{
            botaoseis.setText("O");
            botaoseis.setEnabled(false);
            posicao[1][2]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaoseisActionPerformed

    private void botaoseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoseteActionPerformed
        //botaosete
        jogadordavez();
        if(op==1){
            botaosete.setText("X");
            botaosete.setEnabled(false);
            posicao[2][0]="x";
        }
        else{
            botaosete.setText("O");
            botaosete.setEnabled(false);
            posicao[2][0]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaoseteActionPerformed

    private void botaooitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaooitoActionPerformed
        //botaooito
        jogadordavez();
        if(op==1){
            botaooito.setText("X");
            botaooito.setEnabled(false);
            posicao[2][1]="x";
        }
        else{
            botaooito.setText("O");
            botaooito.setEnabled(false);
            posicao[2][1]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaooitoActionPerformed

    private void botaonoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaonoveActionPerformed
        //botaonove
        jogadordavez();
        if(op==1){
            botaonove.setText("X");
            botaonove.setEnabled(false);
            posicao[2][2]="x";
        }
        else{
            botaonove.setText("O");
            botaonove.setEnabled(false);
            posicao[2][2]="o";
        }
        vencedor();
    }//GEN-LAST:event_botaonoveActionPerformed

    
    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        //Reiniciar
        botaoum.setText("");
        botaoum.setEnabled(true);
        
        botaodois.setText("");
        botaodois.setEnabled(true);
        
        botaotres.setText("");
        botaotres.setEnabled(true);
        
        botaoquatro.setText("");
        botaoquatro.setEnabled(true);
        
        botaocinco.setText("");
        botaocinco.setEnabled(true);
        
        botaoseis.setText("");
        botaoseis.setEnabled(true);
        
        botaosete.setText("");
        botaosete.setEnabled(true);
        
        botaooito.setText("");
        botaooito.setEnabled(true);
        
        botaonove.setText("");
        botaonove.setEnabled(true);
        
        limpaPosicao();
        visor.setText("Comece novamente");
    }//GEN-LAST:event_ReiniciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogodaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogodaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogodaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogodaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable() {
            public void run() {
                new JogodaOld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reiniciar;
    private javax.swing.JButton botaocinco;
    private javax.swing.JButton botaodois;
    private javax.swing.JButton botaonove;
    private javax.swing.JButton botaooito;
    private javax.swing.JButton botaoquatro;
    private javax.swing.JButton botaoseis;
    private javax.swing.JButton botaosete;
    private javax.swing.JButton botaotres;
    private javax.swing.JButton botaoum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}